---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
library(stringr)
```

```{r}
data("rest_inspec")
  rest_inspec = 
  rest_inspec %>%
  select(boro, cuisine_description, inspection_date, violation_description, score, grade) %>%
  filter(
    boro=="MANHATTAN",
    inspection_date > '2017-06-01:2017-09-22',
    cuisine_description != "Bottled beverages, including water, sodas, juices, etc.",
    cuisine_description != "Latin (Cuban, Dominican, Puerto Rican, South & Central American)"
  ) %>%
  na.omit()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Health Score by Cuisine

```{r}
rest_inspec |>
  plot_ly(y= ~score, color= ~cuisine_description, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Health Score and Grade over Time

```{r}
rest_inspec |>
  plot_ly(
    x= ~inspection_date, y= ~score, type= "scatter", mode=
      "markers", color= ~grade, alpha=0.5)
```

### Number of Inspections by Cuisine

```{r}
rest_inspec |>
  count(cuisine_description) |>
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) |>
  plot_ly(x = ~cuisine_description, y= ~n, color= ~cuisine_description, type = "bar", colors = "viridis")
```

